apiVersion: apps/v1
kind: Deployment
metadata:
  name: sercan
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sercan
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 50%    
  template:
    metadata:
      labels:
        app: sercan
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        imagePullPolicy: Always
        name: sercan
        ports:
        - containerPort: 8080
