##################################################
# RollingUpdate Service - Manifest
##################################################
apiVersion: v1
kind: Service
metadata:
  name: sercan-rolling-testing
  namespace: default
spec:
  selector:
    app: roolingupdate
  type: NodePort
  ports:
  - name: sercan-rolling-testing
    protocol: TCP
    port: 80
    targetPort: 5000 
    nodePort: 3000
